Hometask for lesson 6
OleksandrBarmakov/Barmakov_hillel_lessons pull request #2
Opened 2022-11-19 17:04 UTC by OleksandrBarmakov

2022-11-19 19:22 UTC, apollyonix requested changes
Не хватает перетасовки колоды и раздачи карт игрокам. Плюс - зачем нам два разных класса с main методами? Получаются две несвязанных между собой точки входа в программу

2022-11-22 13:03 UTC, OleksandrBarmakov commented
понял. у меня проблемы со светом, поэтому так затягиваются домашки и фиксы к ним :(

2022-11-30 17:37 UTC, apollyonix approved these changes

2022-11-30 17:37 UTC, apollyonix commented on src/ua/hillel/lesson6/Players.java
> +    String playerName;
можно скрыть поля, сделав их приватными, а наружу предоставить только методы для доступа к ним. так более корректно)

2022-11-30 17:37 UTC, merged